### ISSUE TITLE
Does this work on a stateful widget?

### ISSUE THREAD

**Issue by chitgoks** [zhengbomo/bmprogresshud#2]
It's weird. i tried this one in a stateful widget but i get null when i instantiate it.
it should work still but just weird.

**Comment by zhengbomo** [comment]
@chitgoks can you show you code?

**Comment by chitgoks** [comment]
sorry i stopped using it. but the code i used is the same one in your sample.

**Comment by saad352** [comment]
I am also not being able to use in a StatefulWidget. When I call `ProgressHud.of(context).show(ProgressHudType.loading, "loading...");`

Getting this response on runtime

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'show' was called on null.`
`E/flutter ( 8223): Receiver: null`
`E/flutter ( 8223): Tried calling: show(Instance of 'ProgressHudType', "loading...")`
`E/flutter ( 8223): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)`
`E/flutter ( 8223): #1      _LoginPageState.showLoadingHud (package:flutter_login_signup/src/loginPage.dart:98:29)`
`E/flutter ( 8223): #2      _LoginPageState.build.<anonymous closure> (package:flutter_login_signup/src/loginPage.dart:391:21))........................`

**Comment by zhengbomo** [comment]
@saad352 
 you must get context on the tree of ProgressHud like 
```
ProgressHud(
  child: Center(
    child: Builder(builder: (context) {
      // context on the tree of ProgressHud
      return RaisedButton(
        onPressed: () {
          ProgressHud.of(context).show(ProgressHudType.loading, "loading...");
        );
     }),
),
```
