### ISSUE TITLE
能做到无需Context或全局Context调用吗？

### ISSUE THREAD

**Issue by 6ag** [zhengbomo/bmprogresshud#3]
老铁，能做到类似iOS里SVProgressHUD那样，在任何地方都能调用吗

**Comment by 6ag** [comment]
显示的文字太多，会导致布局溢出错误，如果能限制HUD最大的尺寸，超出可滚动就好了

**Comment by 6ag** [comment]
老铁，把 `showAndDismiss` 方法里根据字符串长度来计算HUD显示时间不是很通用啊，有时候后端返回的错误信息里包含一大堆日志。加个 `static` 变量来设置自动隐藏HUD的间隔时间会更好一些。

**Comment by zhengbomo** [comment]
我加一个最长显示时间属性

**Comment by zhengbomo** [comment]
<img width="472" alt="sss" src="https://user-images.githubusercontent.com/4704147/81464370-ad5f3600-91f3-11ea-951a-bbacdc9edbe3.png">

字符串太长会换行啊，如果是一大堆日志信息，不应该展示给用户，最好给个友好提示

**Comment by 6ag** [comment]
就这样挺好啊，小公司后端返回的错误信息不可控，有些把异常信息都返回了

**Comment by zhengbomo** [comment]
progresshud实现的是跟页面走的，暂时没有全局的对象，可以自己维护一个

**Comment by zhengbomo** [comment]
> 就这样挺好啊，小公司后端返回的错误信息不可控，有些把异常信息都返回了

给友好提示啊

**Comment by nslogx** [comment]
@6ag https://github.com/huangjianke/flutter_easyloading
