### ISSUE TITLE
UI freeze after 20+ times of invocations

### ISSUE THREAD

**Issue by ywdeng** [zhengbomo/bmprogresshud#5]
I use ProgressHud to wrap an asynchronous REST API call, after 20 or more times of query, the UI freezes.
My code looks like:

final GlobalKey<ProgressHudState> _hudKey = GlobalKey();
...
body: ProgressHud(
  key: _hudKey,
  child: SingleChildScrollView(
    child: Column(
    ...
    _hudKey.currentState?.show(ProgressHudType.loading, 'Query...');
    StationModel m = await findStationByID(stationID);
    _hudKey.currentState?.dismiss();

**Comment by zhengbomo** [comment]
@ywdeng can you show the fullcode?

**Comment by zhengbomo** [comment]
@ywdeng is version 1.0.0 fixed?
